resources:
  - ../../base/prod-nginx

patches:
  - path: ram-patch.yaml
    target:
      kind: Deployment
      name: nginx-prod
  - target:
      kind: Deployment
      name: nginx-prod
    path: replicas.yaml

