apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
spec:
  template:
    spec:
      containers:
        - name: nginx-prod
          resources:
            requests:
              memory: "256Mi"
