apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-prod
  namespace: testje
spec:
  template:
    spec:
      containers:
      - name: nginx
        resources:
          requests:
            memory: "300Mi"
