resources:
  - ../../base

replacements:
  - source:
      path: image-replace.yaml
      fieldPath: spec.template.spec.containers.name=nginx.image
    targets:
      - select:
          kind: Deployment
          name: nginx-qa
        fieldPaths:
          - spec.template.spec.containers.name=nginx.image
